server:
  port: 8080
spring:
  application:
    name: messageboard
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: false
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yu
    url: jdbc:mysql://localhost:3306/messageboard?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    nwpu.messageboard.mapper: DEBUG

jwt:
  #  jwt工具类加密用的密码
  secret: nwpu
  #  jwt工具类设定的有效时间,以天为单位
  expiration: 7