server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://120.46.41.215:3306/system_db
    username: root
    password: 20030730Pzm.
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.223.129 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 20030730Pzm. # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

minio:
  endpoint: http://localhost:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

logging:
  level:
    root: info
    com.system.repair_person: debug

logstash:
  host: localhost
  enableInnerLog: false